// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Non-pooling URL required for migrations (pgbouncer doesn't support DDL)
    url: process.env["SUPABASE_POSTGRES_URL_NON_POOLING"],
  },
});
